---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version
      when: not dry_run

    - debug:
        var: kernel_version.stdout_lines
      when: not dry_run


- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "port_provision_100g_10g_25g_50g_cr_fec_cl91_autoneg_off_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true

  tasks:
    - file:
        path: "{{ port_provision_log_dir }}"
        state: directory
      when: not dry_run

    - name: Copy port provisioned interfaces_100g_10g_25g_50g_cr_fec_cl91_autoneg_off file to /etc/network/interfaces
      template:
        src: "../../files/{{ inventory_hostname }}/interfaces_100g_10g_25g_50g_cr_fec_cl91_autoneg_off"
        dest: "{{ network_interfaces_file }}"
      when: not dry_run

    - name: Copy goesd-platina-mk1-modules.conf file
      template:
        src: "../../files/goesd-platina-mk1-modprobe.conf_100g_10g_25g_50g"
        dest: "{{ goesd_modprobe_file }}"
      when: not dry_run

    - name: Update interfaces file for fiber ports
      test_fiber_ports:
        cmd : "1,1,4,1,4,1,2,1,4,1,4,1,4,1,2,1,1,1,4,1,4,1,2,1,4,1,4,1,4,1,2,1"
      register: fmodule_out

    - name: Restart goes
      command: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - "modprobe platina-mk1 provision={{ fmodule_out.hash_dict['command'] }}"
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'
      when: not dry_run
      
    - set_fact: 
        commands: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - "modprobe platina-mk1 provision={{ fmodule_out.hash_dict['command'] }}"
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'
      when: dry_run

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10
      when: not dry_run

    - name: Goes status
      command: goes status
      register: result
      retries: "{{ goes_retry }}"
      delay: "{{ goes_delay }}"
      until: result.rc == 0
      when: not dry_run

    - name: Verify media, speed and fec values
      test_multi_port_links:
        switch_name: "{{ inventory_hostname }}"
        speed: "100g,10g,20g,25g,50g,1g"
        f_ports: "{{ fmodule_out.hash_dict['eth_list'] }}"
        media: "copper"
        fec: "cl74"
        platina_redis_channel: "{{ platina_redis_channel }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
      register: module_out
      when: not dry_run

    - name: Verify media, speed and fec values
      test_multi_port_links:
        switch_name: "{{ inventory_hostname }}"
        speed: "100g,10g,20g,25g,50g,1g"
        media: "copper"
        fec: "cl74"
        platina_redis_channel: "{{ platina_redis_channel }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
        dry_run_mode: "{{ dry_run }}"
      register: dry_run_out
      delegate_to: 127.0.0.1
      when: dry_run

    - set_fact:
        dry_run_cmds: "{{ dry_run_out.cmds }}"
      when: dry_run

    - command: "date +%Y%m%d%T"
      register: end_time
      when: not dry_run

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs
      when: not dry_run

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      when: not dry_run

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes


- hosts: spine
  become: true
  tasks:
    - name: Initiate iperf servers
      shell: "iperf -s &"
      when: not dry_run

    - set_fact:
        iperf_cmd: "iperf -s &"
      when: dry_run

- hosts: leaf[0]
  become: true
  tasks:
    - name: Initiate iperf client and verify traffic
      verify_iperf_traffic_multi:
        switch_name: "{{ inventory_hostname }}"
        eth_ips_last_octet: "31,32"
        speed: "100g,10g,20g,25g,50g,1g"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
      register: module_out
      when: not dry_run

    - name: Initiate iperf client and verify traffic
      verify_iperf_traffic_multi:
        switch_name: "{{ inventory_hostname }}"
        eth_ips_last_octet: "31,32"
        speed: "100g,10g,20g,25g,50g,1g"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ port_provision_log_dir }}"
        dry_run_mode: "{{ dry_run }}"
      register: idry_run_out
      delegate_to: 127.0.0.1
      when: dry_run

    - set_fact:
        idry_run_cmds: "{{ idry_run_out.cmds }}"
      when: dry_run

    - command: "date +%Y%m%d%T"
      register: end_time
      when: not dry_run

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs
      when: not dry_run

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      when: not dry_run

    - copy:
        src: "../../files/show_tech.py"
        dest: /tmp/show_tech.py
        mode: 0755
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - command: "/tmp/./show_tech.py --path /var/log/show_tech/ --hash_name {{ hostvars['server_emulator']['hash_name'] }}"
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes

    - file:
        path: /tmp/show_tech.py
        state: absent
      when: module_out.hash_dict['result.status'] == "Failed"
      ignore_errors: yes


- include: port_provision_reset.yml
  when:
    - reset_config
    - not dry_run


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result
      when: not dry_run

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"
      when: not dry_run

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"
      when: not dry_run

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"
      when: not dry_run


- hosts: leaf:spine
  become: true
  vars:
    modeprobe_file: "{{ lookup('file', '../../files/goesd-platina-mk1-modprobe.conf_100g_10g_25g_50g') }}"
  tasks:
    - include: ../../playbooks/get_goes_status.yml start_time={{ hostvars['server_emulator']['start_time'] }} hash_name={{ hostvars['server_emulator']['hash_name'] }}
      when: not dry_run

    - name: Print modeprobe.config
      debug:
        var: modeprobe_file
      when: dry_run
      delegate_to: 127.0.0.1

    - name: Print commands executed
      debug:
        var: commands
      when: dry_run
      delegate_to: 127.0.0.1

    - name: Print dry run commands
      debug:
        var: dry_run_cmds
      delegate_to: 127.0.0.1
      when: dry_run

    - name: Print iperf command
      debug:
        var: iperf_cmd
      delegate_to: 127.0.0.1
      when: dry_run

    - name: Print iperf check commands
      debug:
        var: idry_run_cmds
      delegate_to: 127.0.0.1
      when: dry_run

- hosts: leaf[0]:spine[0]
  become: true
  vars:
    interfaces_file: "{{ lookup('file', '../../files/{{ inventory_hostname }}/interfaces_100g_10g_25g_50g_cr_fec_cl91_autoneg_off') }}"
  tasks:
    - name: Print interfaces file
      debug:
        var: interfaces_file
      when: dry_run
      delegate_to: 127.0.0.1

