---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version
      when: not dry_run

    - debug:
        var: kernel_version.stdout_lines
      when: not dry_run

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Download the goes coreboot downgrade file
      get_url:
        url: "http://172.17.2.28/downloads/v0.4/coreboot-platina-mk1.rom"
        dest: "{{ goes_installer_dir }}{{ goes_coreboot_installer_name }}"
        mode: 0755
 
    - name: Run the downgrade file to downgrade coreboot version
      shell: "/usr/local/sbin/flashrom -p internal -l /usr/local/share/flashrom/layouts/platina-mk1.xml -i bios -w {{ goes_installer_dir }}./{{ goes_coreboot_installer_name }} -A -V"
      register: downgrade
 
    - name: Remove coreboot downgrade script
      shell: "rm -f /tmp/{{ goes_coreboot_installer_name }}"
   
    - name: reboot the switch
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for switch to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15
      
    - name: Check version
      shell: goes upgrade -r
      register: input

    - debug:
        var: input.stdout_lines

    - debug:
        msg: "coreboot Downgraded successfully"
      when: "'Version :  v0.4' in input.stdout"

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "Coreboot Upgrade: Coreboot Downgraded Successfully "
      delegate_to: 127.0.0.1
      when: "'Version :  v0.4' in input.stdout"

    - name: Check goes status
      shell: goes status
      register: result_out

    - name: Print goes status
      debug:
        var: result_out

    - name: Verify link status b/w invaders
      verify_links:
        switch_name: "{{ inventory_hostname }}"
        leaf_list: "{{ groups['leaf'] }}"
        eth_list: "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31"
        platina_redis_channel: "{{ platina_redis_channel }}"
      register: module_out

    - name: Print Link Status
      debug:
        var: module_out

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "Links Status {{ inventory_hostname }}: {{ module_out.msg }}"
      delegate_to: 127.0.0.1
